# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fs_sessions', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS "analytics"', migrations.RunSQL.noop),
        # Search services use TrigramSimilarity in addition to full-text search.
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm', migrations.RunSQL.noop),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('result_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField()),
                ('selected_result', models.BooleanField(default=False)),
                ('search_latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kiosk_session', models.ForeignKey(blank=True, db_column='kiosk_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to='fs_sessions.kiosksession')),
                ('room', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to='map.room')),
            ],
            options={
                'db_table': '"analytics"."search_events"',
                'indexes': [models.Index(fields=['-created_at'], name='idx_search_events_created'), models.Index(fields=['resolved'], name='idx_search_events_resolved')],
            },
        ),
    ]
