# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('fs_sessions', '0001_initial'),
        ('hardware', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('route_distance', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('route_generation_ms', models.IntegerField(blank=True, null=True)),
                ('destination_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('generated', 'Generated'), ('failed', 'Failed'), ('completed', 'Completed')], default='requested', max_length=30)),
                ('navigation_session', models.ForeignKey(blank=True, db_column='navigation_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_requests', to='fs_sessions.navigationsession')),
                ('origin_node', models.ForeignKey(blank=True, db_column='origin_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_requests_originating', to='map.node')),
            ],
            options={
                'db_table': '"analytics"."navigation_requests"',
            },
        ),
        migrations.CreateModel(
            name='NavigationDestination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination_order', models.IntegerField()),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('destination_node', models.ForeignKey(db_column='destination_node_id', on_delete=django.db.models.deletion.RESTRICT, related_name='navigation_destinations', to='map.node')),
                ('navigation_request', models.ForeignKey(db_column='navigation_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='analytics.navigationrequest')),
            ],
            options={
                'db_table': '"analytics"."navigation_destinations"',
            },
        ),
        migrations.CreateModel(
            name='QrEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('generated', 'Generated'), ('scanned', 'Scanned'), ('expired', 'Expired'), ('invalid', 'Invalid')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('navigation_session', models.ForeignKey(blank=True, db_column='navigation_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_events', to='fs_sessions.navigationsession')),
            ],
            options={
                'db_table': '"analytics"."qr_events"',
            },
        ),
        migrations.CreateModel(
            name='SensorStatistic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('average_density', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('peak_density', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('average_signal_count', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('peak_signal_count', models.IntegerField(blank=True, null=True)),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hardware.sensor', to_field='device_id')),
            ],
            options={
                'db_table': '"analytics"."sensor_statistics"',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('alert_type', models.CharField(choices=[('informational', 'Informational'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, db_column='acknowledged_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='authentication.adminuser')),
            ],
            options={
                'db_table': '"operations"."alerts"',
                'indexes': [models.Index(condition=models.Q(('cleared_at__isnull', True)), fields=['-created_at'], name='idx_alerts_active')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('asset', 'Asset'), ('configuration', 'Configuration'), ('validation', 'Validation'), ('administrative', 'Administrative')], max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('replace', 'Replace'), ('restore', 'Restore'), ('validate', 'Validate'), ('activate', 'Activate'), ('deactivate', 'Deactivate')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, db_column='admin_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='authentication.adminuser')),
            ],
            options={
                'db_table': '"analytics"."audit_events"',
                'indexes': [models.Index(fields=['-created_at'], name='idx_audit_events_created'), models.Index(fields=['admin_user'], name='idx_audit_events_user'), models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_events_entity'), models.Index(fields=['event_type', '-created_at'], name='idx_audit_events_type_time')],
            },
        ),
        migrations.CreateModel(
            name='HourlyKioskStatistic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour_start', models.DateTimeField()),
                ('session_count', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('successful_searches', models.IntegerField(default=0)),
                ('failed_searches', models.IntegerField(default=0)),
                ('qr_generated', models.IntegerField(default=0)),
                ('qr_scanned', models.IntegerField(default=0)),
                ('average_session_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('kiosk', models.ForeignKey(blank=True, db_column='kiosk_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_statistics', to='hardware.kiosk', to_field='device_id')),
            ],
            options={
                'db_table': '"analytics"."hourly_kiosk_statistics"',
                'constraints': [models.UniqueConstraint(fields=('hour_start', 'kiosk'), name='hourly_kiosk_statistics_pk')],
            },
        ),
        migrations.AddIndex(
            model_name='navigationrequest',
            index=models.Index(fields=['-started_at'], name='idx_navigation_requests_time'),
        ),
        migrations.AddConstraint(
            model_name='navigationdestination',
            constraint=models.UniqueConstraint(fields=('navigation_request', 'destination_order'), name='navigation_destinations_request_order_uq'),
        ),
        migrations.AddIndex(
            model_name='qrevent',
            index=models.Index(fields=['-created_at'], name='idx_qr_events_created'),
        ),
        migrations.AddConstraint(
            model_name='sensorstatistic',
            constraint=models.UniqueConstraint(fields=('period_start', 'sensor'), name='sensor_statistics_pk'),
        ),
    ]
