# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("authentication", "0002_spec_check_constraints"),
        ("fs_sessions", "0002_spec_check_constraints"),
        ("map", "0002_spec_check_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("severity__in", ["informational", "warning", "critical"])
                ),
                name="chk_alerts_severity",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("alert_type__in", ["informational", "warning", "critical"])
                ),
                name="chk_alerts_alert_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        ["asset", "configuration", "validation", "administrative"],
                    )
                ),
                name="chk_audit_events_event_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "create",
                            "update",
                            "delete",
                            "upload",
                            "replace",
                            "restore",
                            "validate",
                            "activate",
                            "deactivate",
                        ],
                    )
                ),
                name="chk_audit_events_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["requested", "generated", "failed", "completed"])
                ),
                name="chk_navigation_requests_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event_type__in", ["generated", "scanned", "expired", "invalid"])
                ),
                name="chk_qr_events_event_type",
            ),
        ),
    ]
