# Generated by Django 5.2.17 on 2026-09-26 09:51

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_spec_check_constraints"),
        ("authentication", "0002_spec_check_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("sections", models.JSONField(default=list)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("filters", models.JSONField(default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("format_version", models.IntegerField(default=1)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="generated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": '"analytics"."reports"',
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_reports_created")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "generating", "completed", "failed"],
                            )
                        ),
                        name="chk_reports_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("format__in", ["pdf", "csv"])),
                        name="chk_reports_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start__lte", models.F("period_end"))
                        ),
                        name="chk_reports_period",
                    ),
                ],
            },
        ),
    ]
