# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=150, unique=True)),
                ('device_type', models.CharField(choices=[('kiosk', 'Kiosk'), ('sensor', 'Sensor')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('online', 'Online'), ('offline', 'Offline'), ('disabled', 'Disabled'), ('decommissioned', 'Decommissioned')], default='unregistered', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('mqtt_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('last_data_at', models.DateTimeField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"hardware"."devices"',
            },
        ),
        migrations.CreateModel(
            name='SensorObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('estimated_density', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('signal_count', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"hardware"."sensor_observations"',
            },
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('device', models.OneToOneField(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kiosk', serialize=False, to='hardware.device')),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('touchscreen_connected', models.BooleanField(blank=True, null=True)),
                ('touchscreen_status', models.CharField(blank=True, max_length=50, null=True)),
                ('orientation', models.CharField(blank=True, max_length=30, null=True)),
                ('hardware_status', models.CharField(blank=True, max_length=50, null=True)),
                ('flowsense_version', models.CharField(blank=True, max_length=50, null=True)),
                ('frontend_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_application_restart_at', models.DateTimeField(blank=True, null=True)),
                ('application_status', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_updated_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_status', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"hardware"."kiosks"',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device', models.OneToOneField(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sensor', serialize=False, to='hardware.device')),
                ('sampling_interval_seconds', models.IntegerField(blank=True, null=True)),
                ('sensor_enabled', models.BooleanField(default=False)),
                ('battery_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('mqtt_status', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=30, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_status', models.CharField(blank=True, max_length=30, null=True)),
                ('last_transmission_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"hardware"."sensors"',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='idx_devices_status'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='idx_devices_type'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosks', to='map.area'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='floor',
            field=models.ForeignKey(blank=True, db_column='floor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosks', to='map.floor'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='map_node',
            field=models.OneToOneField(blank=True, db_column='map_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk', to='map.node'),
        ),
        migrations.AddField(
            model_name='sensorobservation',
            name='sensor',
            field=models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hardware.sensor', to_field='device_id'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='map.area'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='floor',
            field=models.ForeignKey(blank=True, db_column='floor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='map.floor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='map_node',
            field=models.OneToOneField(blank=True, db_column='map_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='map.node'),
        ),
        migrations.AddIndex(
            model_name='kiosk',
            index=models.Index(fields=['map_node'], name='idx_devices_map_lookup'),
        ),
        migrations.AddIndex(
            model_name='sensorobservation',
            index=models.Index(fields=['sensor', '-observed_at'], name='idx_sensor_obs_sensor_time'),
        ),
        migrations.AddIndex(
            model_name='sensorobservation',
            index=models.Index(fields=['-observed_at'], name='idx_sensor_observations_time'),
        ),
    ]
