# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
        ("map", "0002_spec_check_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("device_type__in", ["kiosk", "sensor"])),
                name="chk_devices_device_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "unregistered",
                            "registered",
                            "online",
                            "offline",
                            "disabled",
                            "decommissioned",
                        ],
                    )
                ),
                name="chk_devices_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mqtt_status__in", ["online", "offline", "unknown"]),
                    ("mqtt_status__isnull", True),
                    _connector="OR",
                ),
                name="chk_sensors_mqtt_status",
            ),
        ),
    ]
