# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS "operations"', migrations.RunSQL.noop),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('super admin', 'Super Admin')], default='admin', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': '"operations"."admin_users"',
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to='authentication.adminuser')),
            ],
            options={
                'db_table': '"operations"."admin_sessions"',
                'indexes': [models.Index(fields=['admin_user'], name='idx_admin_sessions_user'), models.Index(fields=['session_token_hash'], name='idx_admin_sessions_token')],
            },
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('otp', 'OTP'), ('login_link', 'Login Link')], max_length=20)),
                ('token_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, db_column='admin_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_challenges', to='authentication.adminuser')),
            ],
            options={
                'db_table': '"operations"."auth_challenges"',
                'indexes': [models.Index(fields=['expires_at'], name='idx_auth_challenges_expires')],
            },
        ),
    ]
