# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="adminuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["admin", "super admin"])),
                name="chk_admin_users_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="authchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenge_type__in", ["otp", "login_link"])),
                name="chk_auth_challenges_challenge_type",
            ),
        ),
    ]
