# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Bootstrap namespaces before creating schema-qualified tables.
        # Keep schemas on rollback: they may contain independently managed data.
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS "campus"', migrations.RunSQL.noop),
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS "navigation"', migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"campus"."personnel"',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_type', models.CharField(choices=[('campus', 'Campus'), ('building', 'Building'), ('outdoor', 'Outdoor'), ('connector', 'Connector')], max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_area', models.ForeignKey(blank=True, db_column='parent_area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_areas', to='map.area')),
            ],
            options={
                'db_table': '"campus"."areas"',
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='map.area')),
            ],
            options={
                'db_table': '"campus"."elevators"',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('entrance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='map.area')),
            ],
            options={
                'db_table': '"campus"."entrances"',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('glb_node_name', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_order', models.IntegerField()),
                ('elevation', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('navigable', models.BooleanField(default=True)),
                ('visible_in_kiosk', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='map.area')),
            ],
            options={
                'db_table': '"campus"."floors"',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('node_type', models.CharField(choices=[('room', 'Room'), ('auxiliary', 'Auxiliary'), ('kiosk', 'Kiosk'), ('sensor', 'Sensor'), ('area_entrance', 'Area Entrance')], max_length=40)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857)),
                ('active', models.BooleanField(default=True)),
                ('navigable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.ForeignKey(db_column='floor_id', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='map.floor')),
            ],
            options={
                'db_table': '"navigation"."nodes"',
            },
        ),
        migrations.CreateModel(
            name='FloorTransition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transition_type', models.CharField(choices=[('stairs', 'Stairs'), ('elevator', 'Elevator'), ('escalator', 'Escalator'), ('other', 'Other')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_node', models.ForeignKey(blank=True, db_column='from_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='map.node')),
                ('to_node', models.ForeignKey(blank=True, db_column='to_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='map.node')),
            ],
            options={
                'db_table': '"navigation"."floor_transitions"',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('forward', 'Forward'), ('reverse', 'Reverse')], default='bidirectional', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, null=True, srid=3857)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_node', models.ForeignKey(db_column='from_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='map.node')),
                ('to_node', models.ForeignKey(db_column='to_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='map.node')),
            ],
            options={
                'db_table': '"navigation"."edges"',
            },
        ),
        migrations.CreateModel(
            name='OutdoorWalkway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('navigable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3857)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_walkways', to='map.area')),
            ],
            options={
                'db_table': '"campus"."outdoor_walkways"',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=100)),
                ('room_alias', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('room', 'Room'), ('office', 'Office'), ('laboratory', 'Laboratory'), ('facility', 'Facility'), ('service', 'Service'), ('restroom', 'Restroom'), ('hall', 'Hall'), ('other', 'Other')], default='room', max_length=50)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_navigable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.ForeignKey(db_column='floor_id', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='map.floor')),
            ],
            options={
                'db_table': '"campus"."rooms"',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='room',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='map.room'),
        ),
        migrations.CreateModel(
            name='RoomPersonnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('personnel', models.ForeignKey(db_column='personnel_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_personnel', to='map.personnel')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_personnel', to='map.room')),
            ],
            options={
                'db_table': '"campus"."room_personnel"',
            },
        ),
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, related_name='stairs', to='map.area')),
            ],
            options={
                'db_table': '"campus"."stairs"',
            },
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['parent_area'], name='idx_areas_parent'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('area', 'floor_order'), name='uq_floor_order'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['from_node'], name='idx_navigation_edges_from'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['to_node'], name='idx_navigation_edges_to'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['active'], name='idx_edges_active'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='chk_edge_nodes_different'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'room_code'), name='uq_room_code_per_floor'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['floor'], name='idx_navigation_nodes_floor'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='idx_navigation_nodes_type'),
        ),
        migrations.AddConstraint(
            model_name='roompersonnel',
            constraint=models.UniqueConstraint(fields=('room', 'personnel'), name='room_personnel_pk'),
        ),
    ]
