# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="area",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("area_type__in", ["campus", "building", "outdoor", "connector"])
                ),
                name="chk_areas_area_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("direction__in", ["bidirectional", "forward", "reverse"])
                ),
                name="chk_edges_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="floortransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "transition_type__in",
                        ["stairs", "elevator", "escalator", "other"],
                    )
                ),
                name="chk_floor_transitions_transition_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "node_type__in",
                        ["room", "auxiliary", "kiosk", "sensor", "area_entrance"],
                    )
                ),
                name="chk_nodes_node_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "room_type__in",
                        [
                            "room",
                            "office",
                            "laboratory",
                            "facility",
                            "service",
                            "restroom",
                            "hall",
                            "other",
                        ],
                    )
                ),
                name="chk_rooms_room_type",
            ),
        ),
    ]
