"""
Step 14 (additive): where each building stands in the campus (placement),
how the kiosk shows a building added from the admin panel (map_settings),
floor names (QA-93), and campus labels placed in Map Annotation.
"""
# Generated by Django 5.2.17 on 2026-09-27 08:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_rooms_search_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="map_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="placement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="short_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="CampusLabel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        db_column="area_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="map.area",
                    ),
                ),
            ],
            options={
                "db_table": '"campus"."labels"',
                "indexes": [models.Index(fields=["area"], name="idx_labels_area")],
            },
        ),
    ]
