# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('idle_timeout', 'Idle Timeout'), ('manual_exit', 'Manual Exit'), ('error', 'Error'), ('unknown', 'Unknown')], max_length=30, null=True)),
                ('kiosk', models.ForeignKey(blank=True, db_column='kiosk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_sessions', to='hardware.kiosk', to_field='device_id')),
            ],
            options={
                'db_table': '"analytics"."kiosk_sessions"',
            },
        ),
        migrations.CreateModel(
            name='NavigationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('scanned', 'Scanned'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk_session', models.ForeignKey(blank=True, db_column='kiosk_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_sessions', to='fs_sessions.kiosksession')),
            ],
            options={
                'db_table': '"operations"."navigation_sessions"',
            },
        ),
    ]
