# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fs_sessions", "0001_initial"),
        ("hardware", "0002_spec_check_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kiosksession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "end_reason__in",
                        [
                            "completed",
                            "idle_timeout",
                            "manual_exit",
                            "error",
                            "unknown",
                        ],
                    ),
                    ("end_reason__isnull", True),
                    _connector="OR",
                ),
                name="chk_kiosk_sessions_end_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "created",
                            "active",
                            "scanned",
                            "completed",
                            "expired",
                            "cancelled",
                        ],
                    )
                ),
                name="chk_navigation_sessions_status",
            ),
        ),
    ]
