# Generated by Django 5.2.7 on 2026-08-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS "assets"', migrations.RunSQL.noop),
        migrations.CreateModel(
            name='AssetAuditHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('admin_user_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': '"assets"."asset_audit_history"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(default='building_model', max_length=50)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='map.area')),
            ],
            options={
                'db_table': '"assets"."assets"',
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('storage_path', models.TextField()),
                ('file_format', models.CharField(max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('object_count', models.IntegerField(blank=True, null=True)),
                ('mesh_count', models.IntegerField(blank=True, null=True)),
                ('material_count', models.IntegerField(blank=True, null=True)),
                ('texture_count', models.IntegerField(blank=True, null=True)),
                ('detected_floor_count', models.IntegerField(blank=True, null=True)),
                ('potential_floor_count', models.IntegerField(blank=True, null=True)),
                ('vertices_count', models.BigIntegerField(blank=True, null=True)),
                ('triangles_count', models.BigIntegerField(blank=True, null=True)),
                ('dimension_x', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('dimension_y', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('dimension_z', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('coordinate_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_engine', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.asset')),
            ],
            options={
                'db_table': '"assets"."asset_versions"',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='active_version',
            field=models.ForeignKey(blank=True, db_column='active_version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_assets', to='assets.assetversion'),
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validated_by', models.BigIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_version', models.ForeignKey(db_column='asset_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='assets.assetversion')),
            ],
            options={
                'db_table': '"assets"."validation_runs"',
            },
        ),
        migrations.CreateModel(
            name='ValidationCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('file_and_format', 'File & Format'), ('model_and_geometry', 'Model & Geometry'), ('hierarchy_and_floor_structure', 'Hierarchy & Floor Structure'), ('floors_and_spatial_configuration', 'Floors & Spatial Configuration'), ('flowsense_compatibility', 'FlowSense Compatibility')], max_length=60)),
                ('check_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(db_column='validation_run_id', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='assets.validationrun')),
            ],
            options={
                'db_table': '"assets"."validation_checks"',
            },
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'version'), name='asset_versions_asset_version_uq'),
        ),
    ]
