# Generated by Django 5.2.17 on 2026-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "processing_status__in",
                        ["pending", "processing", "completed", "failed"],
                    )
                ),
                name="chk_asset_versions_processing_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        [
                            "file_and_format",
                            "model_and_geometry",
                            "hierarchy_and_floor_structure",
                            "floors_and_spatial_configuration",
                            "flowsense_compatibility",
                        ],
                    )
                ),
                name="chk_validation_checks_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["passed", "warning", "error"])),
                name="chk_validation_checks_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("result__in", ["passed", "warning", "failed"])),
                name="chk_validation_runs_result",
            ),
        ),
    ]
