"""operations.settings and operations.semesters, owned by `common`.

These tables were first created by a `configuration` app, which was folded into
`common` to match the API design ("common/settings"). The table names are
unchanged, so this migration creates them only where they don't exist yet:
- on a fresh database it creates them;
- on a database that ran the old `configuration` migrations it keeps them (and
  their data) and removes the stale `configuration` migration records.
"""
import django.db.models.deletion
from django.db import migrations, models

CREATE_TABLES = """
CREATE SCHEMA IF NOT EXISTS "operations";
CREATE TABLE IF NOT EXISTS "operations"."semesters" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "academic_year" varchar(20) NOT NULL,
    "name" varchar(100) NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "chk_semesters_date_range" CHECK ("start_date" <= ("end_date"))
);
CREATE TABLE IF NOT EXISTS "operations"."settings" (
    "key" varchar(100) NOT NULL PRIMARY KEY,
    "value" jsonb NOT NULL,
    "description" text NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "updated_by" bigint NULL
);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'settings_updated_by_1cab9c01_fk_admin_users_id'
    ) THEN
        ALTER TABLE "operations"."settings"
            ADD CONSTRAINT "settings_updated_by_1cab9c01_fk_admin_users_id"
            FOREIGN KEY ("updated_by") REFERENCES "operations"."admin_users" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS "settings_key_f16b5bae_like" ON "operations"."settings" ("key" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "settings_updated_by_1cab9c01" ON "operations"."settings" ("updated_by");
DELETE FROM "django_migrations" WHERE "app" = 'configuration';
"""

DROP_TABLES = """
DROP TABLE IF EXISTS "operations"."settings";
DROP TABLE IF EXISTS "operations"."semesters";
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_spec_check_constraints"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(CREATE_TABLES, DROP_TABLES)],
            state_operations=[
                migrations.CreateModel(
                    name="Semester",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("academic_year", models.CharField(max_length=20)),
                        ("name", models.CharField(max_length=100)),
                        ("start_date", models.DateField()),
                        ("end_date", models.DateField()),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": '"operations"."semesters"',
                        "ordering": ["-start_date"],
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(("start_date__lte", models.F("end_date"))),
                                name="chk_semesters_date_range",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="Setting",
                    fields=[
                        ("key", models.CharField(max_length=100, primary_key=True, serialize=False)),
                        ("value", models.JSONField()),
                        ("description", models.TextField(blank=True, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "updated_by",
                            models.ForeignKey(
                                blank=True,
                                db_column="updated_by",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to="authentication.adminuser",
                            ),
                        ),
                    ],
                    options={"db_table": '"operations"."settings"'},
                ),
            ],
        ),
    ]
